import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PortalNavbar from "./components/header/PortalNavbar";
import PortalFooterCard from "./components/cards/PortalFooterCard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PortalNavbar />
            {children}
        <PortalFooterCard />
      </body>
    </html>
  );
}
